### ISSUE TITLE
IntelliSence doesn't work for MQL 4 after #include

### ISSUE THREAD

**Issue by RenIfx** [L-I-V/MQL-Tools#19] opened 2023-02-26 17:12 UTC
Hello, I started using your extension, I noticed that IntelliSense does not work for MQL4. after #include <C:\Users\User\AppData....... Doesn't offer references to functions and variables, and doesn't work for renaming variables and functions. But for MQL5 everything works. But does not work after editing MQL4 with #include.......
Except for String, String does not work in MQL5 and MQL4.
Are you planning to solve the issue with INCLUDE for MQL4.
And decide with a string?
Thank you so much for writing this extension.

**Comment by L-I-V** [comment] 2023-03-04 10:04
Hi RenIfx, there is no difference between MQL4 and MQL5 in working with #include. Perhaps there is a problem with the path to the include files.
'MQL Tools' is not responsible for providing links to functions, variables, and renaming them. This is done by the 'C/C++' extension.
Regarding IntelliSense for MQL4, variable, constant, and function descriptions for MQL4 will be added in the update.
The 'String' problem will also be resolved in update.

**Comment by RenIfx** [comment] 2023-03-04 13:21
Hi L-I-V. There are no problems with the path to include files. (the path is written in full <c: / / / / /mh4>). Because in MetaEditor 4 everything works fine.
![image](https://user-images.githubusercontent.com/91544971/222903964-5dabde77-6989-48fe-8928-4a6897b8cfbe.png)

At the moment, I only solve this problem by commenting out #include:
//#include <c: / / / / /mh4>
![image](https://user-images.githubusercontent.com/91544971/222903987-fcdf9542-3b8f-49bd-a8a7-a2dfd615eed2.png)

Thanks a lot for your works.

**Comment by L-I-V** [comment] 2023-03-04 15:08
Why do you specify the full path to the 'mqh' file <C:\Users\User\AppData\Roaming\MetaQuotes\Terminal\A80FB02CDD193132189CFCD69D34C571\MQL4\Include\Drow_ar.mqh>?
If 'C:\Users\User\AppData\Roaming\MetaQuotes\Terminal\A80FB02CDD193132189CFCD69D34C571\MQL4' is your working directory, in the settings.json file which is in the .vscode folder specify the following settings: 
"C_Cpp.default.includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}/Include"
    ]
After that you can use an abbreviated notation in your code: #include <Drow_ar.mqh>.

As for your problem, it is probably caused by an error of 'string', 'datetime' or 'color' types in the 'Drow_ar.mqh' file. The problem with the types will be partially solved in an update which will be released within a few days.

**Comment by RenIfx** [comment] 2023-03-04 18:33
OK. Thank you
I will wait for the update.

**Closed** 2023-04-06 16:20 UTC
