### ISSUE TITLE
Auto-complete issues

### ISSUE THREAD

**Issue by trustfultrading** [L-I-V/MQL-Tools#21] opened 2023-03-07 10:33 UTC
First of all, thank you for the great work. I run a youtube channel in the field of automated trading with MetaTrader. I would like to present your extension, however, I have encountered a few small bugs.

1. input variables are not suggested.
<img width="312" alt="2023-03-07 10_36_06-● VSCTest mq5 - MQL5 - Visual Studio Code" src="https://user-images.githubusercontent.com/116789180/223394397-9e9c89ee-bea9-49dd-b422-f9dca083bf18.png">

2. "sinput" is not recognized as a keyword. ENUM_INIT_RETCODE is not suggested.
<img width="459" alt="2023-03-07 10_39_13-● VSCTest mq5 - MQL5 - Visual Studio Code" src="https://user-images.githubusercontent.com/116789180/223394740-75b8b3ff-3d03-4386-b38f-3c581f6905ce.png">

3. classes/structures from include files are not displayed. 
<img width="304" alt="2023-03-07 10_42_00-● VSCTest mq5 - MQL5 - Visual Studio Code" src="https://user-images.githubusercontent.com/116789180/223394818-34e48062-e037-4138-9ae1-3165520fe520.png">

4. if files are mutually included, variables are no longer suggested.
<img width="683" alt="2023-03-07 10_59_23-● VSCTest mq5 - MQL5 - Visual Studio Code" src="https://user-images.githubusercontent.com/116789180/223394839-1460fca7-0115-494d-bb75-a2c522da4382.png">

I hope this is helpful. Is there any way to support you with a donation?

**Comment by L-I-V** [comment] 2023-03-08 10:31
Hi trustfultrading, all these bugs will be fixed in the new version of the extension. To solve the issue mentioned in point 4, try applying such a construction in the TestGUI.mqh file.
```cpp
//###<Experts/Test/VSCTest.mq5>
#ifndef TestGUI_mqh
#define TestGUI_mqh

// your code

#endif
```
Regarding donations, I will include a link to it in the extension description.

**Comment by trustfultrading** [comment] 2023-03-08 15:15
Oh, and is there a way to contact you? You can also contact me via youtube/telegram, I just don't want to write about topics outside of this Extension here on github.

**Comment by fbravohz** [comment] 2023-03-09 04:30
I would like to add something to this issue. When youre trying to access to a function's method, insted of auto completing with object.function() it autocompletes with object->function(). Is this a bug or a problem with my configuration of the extension?

![image](https://user-images.githubusercontent.com/68574419/223917365-977e08fb-9a9a-45bb-b923-10e5fdcababe.png)

**Comment by L-I-V** [comment] 2023-03-11 08:11
Hi trustfultrading.

The issue is that the IntelliSense feature in the 'MQL Tools' extension requires the 'C/C++' extension to be installed. However, due to the fact that the MQL syntax is not fully supported by the 'C/C++' extension, there are problems with the IntelliSense functionality for MQL code.
When adding the file 'VSCTest.mq5' as #include in the file 'TestGUI.mqh', the 'C\C++' extension finds an error 'include file ... includes itself'. That's why I suggested to use preprocessor directive to eliminate this error, because of which auto-completion did not work.

Alternatively, try not to include 'VSCTest.mq5' in 'TestGUI.mqh':
![VSCTest](https://user-images.githubusercontent.com/114299712/224467077-03de05a2-c58b-4e4e-8a6f-b3a5c2d757b1.gif)

Unfortunately, at this moment I do not have a solution for a complete adaptation of extension "C\C++" for MQL syntax.
You can contact me via email at l.i.v.dpro@gmail.com.

**Comment by L-I-V** [comment] 2023-03-11 08:12
Hi fbravohz. I haven't encountered this problem, so I can't say for sure why it's happening. But since auto-completion is a part of the 'C\C++' extension, I suggest checking its settings.

**Comment by trustfultrading** [comment] 2023-03-11 14:04
Hi L-I-V,
thanks for the answer. I'll omit the duplicate include statements, I can live with that. I also deactivated the red underlining and the display of these incorrectly recognized errors in the minimap and explorer:

<img width="557" alt="2023-03-11 14_35_36-VSCTestSignal mqh - MQL5 - Visual Studio Code" src="https://user-images.githubusercontent.com/116789180/224487978-84513ba4-7965-489a-9146-e2f6f39bcc17.png">

<img width="703" alt="2023-03-11 14_29_02-settings json - MQL5 - Visual Studio Code" src="https://user-images.githubusercontent.com/116789180/224487640-67062c49-25c9-4b92-afb9-5062ddd10180.png">

<img width="557" alt="2023-03-11 14_38_30-VSCTestSignal mqh - MQL5 - Visual Studio Code" src="https://user-images.githubusercontent.com/116789180/224487986-542f2a36-78c5-4206-b19a-3d039d48636c.png">


I'm really no expert, but maybe this will help someone :)

Thank you for your great work!

**Comment by L-I-V** [comment] 2023-03-11 15:54
According to the screenshots, you have painted over the underlines indicating errors and warnings displayed by the "MQL Tools" extension, for which the data are provided by MetaEditor.
To hide error underlines, disable this option in the settings of the "MQL Tools" extension:
![Code_YHSnYg8zjR](https://user-images.githubusercontent.com/114299712/224492048-bd0c7914-59eb-4ed3-880f-acb5dd1bd16e.png)

**Comment by trustfultrading** [comment] 2023-03-11 17:29
Didn't see there was already a setting for this. Thanks again!

**Closed** 2023-03-21 09:26 UTC
