### ISSUE TITLE
F1 Help not working

### ISSUE THREAD

**Issue by mishaxz** [L-I-V/MQL-Tools#2] opened 2022-10-15 14:52 UTC
Hi, great stuff here.. 

I have everything working except that F1 doesn't open the help (currently I'm trying in MQL4 but I think for 5 it also doesn't)

Any ideas what I should configure for this?

Compiling works fine.

**Comment by L-I-V** [comment] 2022-10-15 18:30
Maybe you have F1 used by another extension. 
Go to the 'keyboard shortcut' by pressing Ctrl+k Ctrl+s and check where F1 is used. There you can also assign another keyboard shortcut to open the help.

**Comment by mishaxz** [comment] 2022-10-16 11:35
Keyboard shortcuts show

```
{
  "key": "f1",
  "command": "mql_tools.help",
  "when": "config.mql_tools.Help.HelpON && resourceExtname == '.mq4' || config.mql_tools.Help.HelpON && resourceExtname == '.mq5' || config.mql_tools.Help.HelpON && resourceExtname == '.mqh'"
}
```

**Comment by L-I-V** [comment] 2022-10-16 14:19
No need to edit extension files!

![keyboard shortcuts](https://user-images.githubusercontent.com/114299712/196040287-48585bdd-f73c-41ba-a51a-2ea14e068f58.png)

**Comment by L-I-V** [comment] 2022-10-17 14:41
This option must be enabled in the extension settings

![HelpOn](https://user-images.githubusercontent.com/114299712/196202079-c7505b16-82b6-4e1c-9789-07542c863853.png)

What happens after you press F1?
Do error messages appear?

**Comment by mishaxz** [comment] 2022-10-17 15:50
yes it was enabled but I just unchecked it and rechecked it just to be sure. Also everything is configured for path of metatrader and I can compile fine.

pressing F1 does nothing. I tried to both have the caret in the middle of the word as well as selecting the word and pressing F!. Both times nothing happens. 

I tried it on StringFormat(), StringSubStr(), EventSetMillisecondTimer(), OnInit() and others

**Comment by mishaxz** [comment] 2022-10-22 10:24
wow that worked.

Any idea what I need to do to fix F1? or should i assign it to another key

**Comment by L-I-V** [comment] 2022-10-22 15:15
Open 'keybindings.json'
![F1](https://user-images.githubusercontent.com/114299712/197346409-b52dad5a-b2b9-4ee8-abf5-a91f1f8d4b2c.gif)
 and if there is f1, delete and save the file and try calling help via F1. If it doesn't help then assign another key, e.g. Shift+F1

**Comment by kalotech** [comment] 2022-11-20 01:45
Hi L-I-V, after the latest update which has fixed Syntax checking for portable MT4, the F1 for Help does not work any more.  I did a clean install of VSCODE as well as MT4.  

**The steps I follow is like this:**
1- Clean install VSCODE
2 - Clean install of MT4
3 - Install your MQL-Tools extension for VSCODE
4 - Set the Metaeditor path and check the portable checkbox
5 - Open any MQL4 or MQH file and check that Syntax checking and compilation work (all works 100%)
6 - Select a MQL language keyword and press F1
6.1 - A short message pops up bottom right hand corner indicating Help file is loading....thereafter nothing ever again....

Tried restarting - no go.

I can see that a files\help folder is created under your extension folder and that the mql4.chm file is coppied over to it, but the help system is currently not working at all....

Even if I try to run it from the Ctrl + Shift + P menu by selecting the word in the code and then MQL: Help from the command prompt, it also does not open the help file....

**Comment by kalotech** [comment] 2022-11-20 06:34
Hi L-I-V,

In regards to my report above, I have done some "investigation" (aka newbie hacking) by adding a few outputs in you "help.js" file just so I can if the path was received correctly and try and find up until where things worked as expected....and I have found the issue, I think :)

When there is a space in the path name, even if the path is correctly received from __define and concatenated, the help file is not accessed....
C:\VS Code\...... will not work with that space between VS and Code
C:\VSCode\..... works 100%

When I remove the space from the path, all works 100% - I honestly do NOT mind removing a space from my file name structure so I would not worry about this any further unless you know of a quick code fix for this to compensate for spaces in the path name.... strangely though with the really installed (non-portable) version of VS Code, there are spaces in the path...

![image](https://user-images.githubusercontent.com/56123637/202889254-106dad88-01d7-4ac5-bd6d-fc93e928e645.png)

![image](https://user-images.githubusercontent.com/56123637/202889258-fc8dcd1f-3e40-400c-913a-ae635eb1b5e7.png)

**Comment by L-I-V** [comment] 2022-11-20 11:55
Hi kalotech. I am grateful to you for the investigation carried out to identify the cause of the error. You've saved me a lot of time. An update with fixes is already on the Marketplace.

**Comment by kalotech** [comment] 2022-11-20 12:04
Once more, thank you so much for your time and generosity!  Stay awesome!

**Closed** 2023-04-06 16:14 UTC
