### ISSUE TITLE
String type reported as error-type by IntelliSense suggestions

### ISSUE THREAD

**Issue by kaloworx** [L-I-V/MQL-Tools#7] opened 2022-11-20 09:51 UTC
Hi their L-I-V,

Me again :)

I just notice that when calling a function that has a string type variable declared such as in the screenshots below, IntelliSense does not refer to it as a string, but rather an error-type.

![image](https://user-images.githubusercontent.com/56123637/202895464-5845139f-ea77-498f-bac3-489736d0bce5.png)

![image](https://user-images.githubusercontent.com/56123637/202895478-1460440d-6140-400a-8bf4-41337226aca5.png)

![image](https://user-images.githubusercontent.com/56123637/202895491-756f49ee-dc15-4b4a-85ee-4c9538ad4637.png)

Also, is there a way to override the CLANG behaviour of adding a space between C and '20,20,20' when formatting the document.  For example, C'20,20,20' refers to a custom colour, but when applying document wide formatting, a space is automatically added between the C and the colour string which breaks the formatting and then the code can't compile as it creates lots of errors everywhere a custom colour was used in this way.

**Comment by L-I-V** [comment] 2022-11-20 14:00
In this case, the error with types has nothing to do with the 'MQL Tools' extension. This IntelliSense from the extension 'C/C++' does not know the type 'string'. 'MQL Tools' associates files '.mq4', '.mq5' and '.mqh' as '.cpp'. Thus, part of the actions with the document is performed by the extension 'C/C++'. IntelliSense from 'MQL Tools' displays only the 'standard' functions, variables, types and constants of MQL5 (For MQL4 I will add later).
Regarding the gaps after formatting the document in custom colors C'20,20,20' and date D'1980.09.19 12:30:23', in the future I plan to create a clang-format for MQL files. In the meantime, there is a function in the extension that removes spaces in colors and dates when checking syntax or compiling, so there are no errors due to spaces.

**Comment by kalotech** [comment] 2022-11-20 14:58
I suspected that much, thanks for confirming the IntelliSense situation.  Do you think this also explains why in certain situations, the suggestions for functions also does not work for example like in this screenshot.  The function is right there, yet IntelliSense does not "see" it nor suggest it for code completion.

![image](https://user-images.githubusercontent.com/56123637/202909318-b6bf5b48-0f1b-461c-ac8b-63b6120cc2a9.png)


Thanks once more for your time and effort you have put into this most useful extensions for MT coders.

**Comment by kalotech** [comment] 2022-11-20 15:20
In respect of the above, the issue seems to only apply to certain MQL4 files, I can't really figure out what the diffs are, but for one it seems that files with #includes in the header causes this, I'm still checking....because if a creation a blank mq4 file and put some functions in it, the suggestions works just fine, but when I open my larger projects which have lots of includes to function libraries, no suggestions any more.... very strange....

**Comment by kalotech** [comment] 2022-11-20 15:39
Further in addition to the above....I tried inserting MQH includes using your context menu, but it seems to be using forward slashes in the path name and not backslashes as it is supposed to...

![image](https://user-images.githubusercontent.com/56123637/202911206-d8a328cb-940d-490a-bf37-768c42467f32.png)

No biggy, I don't use it, but just thought I'd mention this as a possible extra bug perhaps?

**Comment by kalotech** [comment] 2022-11-20 16:12
Uuugh, for now I will be giving up.... #includes seem to be a huge problem and works intermittently, I just can't spot a pattern.  If there is a special way to include mqh libraries please let me know....thanks for now.

**Comment by kalotech** [comment] 2022-11-20 17:07
Good news, I got all my #includes working accept for the two MQH libraries who have #import functions in them....MetaEditor requires a #import statement to be closed by issuing another second #import at the end of the declaration, like in the screenshot below....When done like this, Intellisense does not make code suggestions if such a MQH files is included which has such an import in it...if I leave the second import out, suggestions work fine, but obviously the code does not compile.... any suggestions ?

![image](https://user-images.githubusercontent.com/56123637/202915534-0affba33-0d65-4566-8fb2-9244c1e8fe0e.png)

**Comment by L-I-V** [comment] 2022-11-23 18:30
Hi kalotech, at the moment I have two solutions and both are not perfect. In my case, the cause of the problem was the 'string' type with the modifier 'input' ('input string'). I replaced 'input' with 'extern' and added a line to the "settings.json" extension settings file: "C_Cpp.default.intelliSenseMode": "windows-gcc-x64". But this way is not very good because it limits the choice of modifier for 'string' type and I can't say it will work for you. In the second method, it is necessary to install the C ++ compiler. This way still needs to be tested because I tested it on one or two files.

**Comment by kalotech** [comment] 2022-11-24 14:07
Hi L-I_V, thanks for getting back to me about this....I will definitely look into these suggestions of yours and get back to you.... this thing is so close to being perfect, I just can't let it go, LOL.... best wishes!

**Comment by kalotech** [comment] 2022-11-30 19:17
Hi @L-I-V ,

I tried your trick with the "C_Cpp.default.intelliSenseMode": "windows-gcc-x64", but regrettably, it did not resolve the problem.

I then installed MinGW and tested the install with the standard HelloWorld cp :) So I know it works and compiles and the path is set correctly etc....

I then created the "C_Cpp.default.intelliSenseMode" json file in the workspace folder and have it set like this:

![image](https://user-images.githubusercontent.com/56123637/204885650-150992b1-3501-43e6-8bdc-115a1a61a9de.png)

Yet still intellisense does not seem to work for STRING's, works fine for INT, DOUBLE etc...

![image](https://user-images.githubusercontent.com/56123637/204885934-20eac156-af18-4270-8cc9-81f496225269.png)
![image](https://user-images.githubusercontent.com/56123637/204885957-b703e510-1c24-4975-98db-d85f9d38ffe9.png)
![image](https://user-images.githubusercontent.com/56123637/204885983-d5b60244-81d6-45c1-b7d8-2da8ff95406e.png)

It also happens that intellisense does not list/recognize all available functions in a MQL file...for example in the screenshot below, on the left in the Outline window there are clearly many functions that start with the letters "btn...", yet intellisense only list one of them....

I know intellisense is a thing on its own and actually has nothing to do with your project, but if you have any other tips or suugestions I could try out, please let me know and I'll dig in.

Best wishes!

**Comment by L-I-V** [comment] 2022-12-01 18:15
Hi kalotech, I managed to add variables and functions with MQL(string, color, datetime) types to the list of IntelliSense suggestions.
![Cl](https://user-images.githubusercontent.com/114299712/205125790-e731a090-18a1-4439-9bbf-4217a0886d68.png)
![Sf](https://user-images.githubusercontent.com/114299712/205125928-8a6e7ce4-47f6-44de-b61d-23c35a049d9d.png)
![CR](https://user-images.githubusercontent.com/114299712/205126150-8b3dee48-2f95-4a3e-926b-7869555a40a7.png)
In the next update I will try to solve most of the problems with IntelliSense, but the update will not be before January 2023.

**Comment by L-I-V** [comment] 2022-12-05 16:47
Hi kalotech, 
This will be part of the next update that will be published in the Marketplace.

**Comment by Ruslan618** [comment] 2022-12-08 23:23
For visible string and other vars i use:

**Closed** 2023-04-06 16:16 UTC
